export const sorveterias = [
    {
        nome:'Sorveteria A',
        endereco:'Rua A',
        foto: require('./img/A.jpg'),
        detalhe:'A melhor sorveteria é realmente excepcional em todos os sentidos! A primeira coisa que me impressionou foi a variedade de sabores disponíveis. Eles oferecem desde os clássicos, como baunilha e chocolate, até opções mais exóticas, como sorvete de lichia e cardamomo. Além disso, a textura e cremosidade dos sorvetes são simplesmente impecáveis. Cada colherada derrete na boca, proporcionando uma experiência deliciosa. O atendimento também merece destaque, pois a equipe é extremamente simpática e prestativa, sempre disposta a ajudar na escolha dos sabores. Sem dúvida, a melhor sorveteria é um lugar que vale a pena visitar para satisfazer os desejos de sorvete.',
        cor: '#7d5fff',
        telefone: "(038)1111-2222",
        avaliacao: 12,
    },
    { 
        nome:'Sorveteria B',
        endereco:'Rua B',
        foto: require('./img/B.jpg'),
        cor: '#c56cf0',
        detalhe:'Visitar a melhor sorveteria foi uma verdadeira explosão de sabores! A variedade de opções é simplesmente incrível. Eles têm sabores para todos os gostos, desde os tradicionais até os mais criativos, como sorvete de creme brûlée e torta de limão. Além disso, a apresentação dos sorvetes é um espetáculo à parte. Eles são servidos de maneira impecável, com coberturas, caldas e até mesmo acompanhamentos especiais, como biscoitos e frutas frescas. A qualidade dos ingredientes também é evidente em cada colherada. Os sorvetes são feitos com ingredientes frescos e naturais, o que torna a experiência ainda mais prazerosa. A melhor sorveteria realmente cumpre seu nome!',
        telefone: "(038)1234-5678",
        avaliacao: 58,
    },
    {
        nome:'Sorveteria C',
        endereco:'Rua C',
        foto: require('./img/C.jpg'),
        cor: '#ff3838',
        detalhe:'A melhor sorveteria é um verdadeiro paraíso para os amantes de sorvete! O ambiente é encantador, com uma decoração alegre e acolhedora que convida a passar horas desfrutando dos sabores deliciosos. A equipe da sorveteria é extremamente dedicada e apaixonada pelo que faz, o que reflete na qualidade dos sorvetes. Cada sabor é cuidadosamente preparado e equilibrado, resultando em uma explosão de sabores na boca. Eles também oferecem opções para pessoas com restrições alimentares, como sorvetes sem lactose e veganos, o que é um diferencial muito positivo. Se você está em busca de uma experiência incrível de sorvete, não deixe de visitar a melhor sorveteria!',
        telefone: "(038)6795-0798",
        avaliacao: 72,
    },
    {
        nome:'Sorveteria D',
        endereco:'Rua D',
        foto: require('./img/D.jpg'),
        cor: '#fff200',
        detalhe:'A melhor sorveteria é simplesmente um sonho realizado para os amantes de sorvete! A primeira coisa que chama atenção é a atmosfera agradável e acolhedora. O local é decorado de forma charmosa, proporcionando um ambiente perfeito para desfrutar dos deliciosos sorvetes. Além disso, a qualidade dos produtos é excepcional. Os sabores são intensos e autênticos, com ingredientes cuidadosamente selecionados. Recomendo experimentar o sorvete de pistache, que é divino! Além dos sorvetes, a melhor sorveteria também oferece sobremesas incríveis, como banana split e sundae, que são verdadeiras tentações. Não há dúvidas de que essa é uma sorveteria que se destaca pela qualidade e sabor dos seus produtos.',
        telefone: "(038)5623-6523",
        avaliacao: 92,
    },
    {
        nome:'Sorveteria E',
        endereco:'Rua E',
        foto: require('./img/E.jpg'),
        cor: '#17c0eb',
        detalhe:'A melhor sorveteria é, de fato, um lugar excepcional para satisfazer a vontade de sorvete. Desde o momento em que você entra, é recebido por um aroma delicioso que vem da cozinha, onde os sorvetes são preparados artesanalmente. A variedade de sabores é impressionante, e cada um deles é uma verdadeira obra de arte. Os sorvetes são cremosos, com uma consistência perfeita, e os sabores são intensos e equilibrados. A melhor sorveteria também oferece opções de coberturas e complementos para deixar seu sorvete ainda mais especial. A equipe é extremamente atenciosa e está sempre pronta para ajudar na escolha dos sabores. Com certeza, um lugar que merece a visita de qualquer amante de sorvete.',
        telefone: "(038)7886-1121",
        avaliacao: 82,
    },
    {
        nome:'Sorveteria F',
        endereco:'Rua F',
        foto: require('./img/F.jpg'),
        cor: '#fffa65',
        detalhe:'A melhor sorveteria é, sem dúvida, um verdadeiro tesouro para os fãs de sorvete. A partir do momento em que você entra, é envolvido por uma atmosfera de doçura e alegria. A decoração é encantadora, com cores vibrantes e detalhes encantadores. No que diz respeito aos sorvetes, eles são simplesmente divinos. Os sabores são intensos e autênticos, proporcionando uma explosão de sabor em cada colherada. Além dos sabores tradicionais, a melhor sorveteria também oferece combinações únicas e criativas, como sorvete de figo com mel e brie. É uma experiência gastronômica única! Não deixe de visitar essa sorveteria incrível e se deliciar com seus sorvetes de alta qualidade.',
        telefone: "(038)6545-8989",
        avaliacao: 62,
    },
]
